final Map<String, String> feelingEmojis = {
  'Happy': '😊',
  'Sad': '😢',
  'Excited': '🤗',
  'Anxious': '😰',
  'Grateful': '🙏',
  'Frustrated': '😤',
  'Content': '😌',
  'Lonely': '😔',
  'Motivated': '💪',
  'Overwhelmed': '😵',
  'Peaceful': '☮️',
  'Angry': '😠',
  'Hopeful': '🌟',
  'Confused': '🤔',
  'Proud': '😎',
  'Disappointed': '😞',
  'Energetic': '⚡️',
  'Curious': '🧐',
  'Stressed': '😩',
  'Joyful': '🥳',
};